"""
Pydantic models for test cases used across the QA pipeline.

These models enforce strict validation on all test case data flowing
through the multi-agent system, ensuring consistent structure between
the Red-Team Agent (generator) and Executor Agent (consumer).
"""

from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum


class EdgeCaseType(str, Enum):
    """Categories of adversarial edge cases the Red-Team Agent targets."""
    BOUNDARY = "boundary"              # Extreme numeric values, limits
    FORMAT_VIOLATION = "format_violation"  # Malformed inputs, wrong types
    MISSING_DATA = "missing_data"      # Null fields, empty documents
    AMBIGUITY = "ambiguity"            # Vague or multi-interpretation inputs
    INJECTION = "injection"            # Prompt injection, SQL injection attempts
    DOMAIN_SPECIFIC = "domain_specific"  # Domain-specific edge cases
    TEMPORAL = "temporal"              # Date-related edge cases
    ENCODING = "encoding"              # Unicode, special characters
    ADVERSARIAL = "adversarial"        # Deliberately misleading inputs


class TestCase(BaseModel):
    """A single test case generated by the Red-Team Agent."""
    id: str = Field(..., description="Unique test case identifier (e.g., TC-001)")
    input_data: str = Field(..., description="The adversarial input to feed to the SUT")
    expected_behavior: str = Field(..., description="What the SUT should ideally do with this input")
    edge_case_type: EdgeCaseType = Field(..., description="Category of the edge case being tested")
    difficulty: str = Field(default="medium", description="Difficulty level: easy, medium, hard")
    rationale: str = Field(default="", description="Why this test case is expected to be challenging")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "TC-001",
                "input_data": "Extract NAV from: 'The fund NAV is approximately $-0.01 per unit as of 31/02/2024'",
                "expected_behavior": "Should flag invalid date (Feb 31) and negative NAV as anomalies",
                "edge_case_type": "boundary",
                "difficulty": "hard",
                "rationale": "Tests handling of impossible dates combined with negative NAV values"
            }
        }


class TestCaseBatch(BaseModel):
    """A batch of test cases from a single Red-Team Agent iteration."""
    test_cases: list[TestCase] = Field(..., description="List of generated test cases")
    iteration: int = Field(..., description="Which iteration these test cases belong to")
    generation_strategy: str = Field(default="", description="The adversarial strategy used this iteration")
